# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

# https://zenn.dev/ganta/articles/e1e0746136ce67
# https://zenn.dev/renoinn/articles/54fc3ed5d3e447

shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.pure]
github = "sindresorhus/pure"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.zsh-git-fzf]
github = "alexiszamanidis/zsh-git-fzf"

[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"

# syntax-highlighting は最後に読み込む
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
